<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AppPercyTosca.Core</RootNamespace>
    <AssemblyName>AppPercyTosca.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="resources/devices.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AppPercyTosca.Core.Tests" />
  </ItemGroup>

</Project>
